export const GET_NEWS_START = "GET_NEWS_START";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_ERROR = "GET_NEWS_ERROR";

export const SEARCH_NEWS_START = "SEARCH_NEWS_START";
export const SEARCH_NEWS_SUCCESS = "SEARCH_NEWS_SUCCESS";
export const SEARCH_NEWS_ERROR = "SEARCH_NEWS_ERROR";

export const CATEGORY_NEWS_START = "CATEGORY_NEWS_START";
export const CATEGORY_NEWS_SUCCESS = "CATEGORY_NEWS_SUCCESS";
export const CATEGORY_NEWS_ERROR = "CATEGORY_NEWS_ERROR";

export const LANGUAGE_NEWS_START = "LANGUAGE_NEWS_START";
export const LANGUAGE_NEWS_SUCCESS = "LANGUAGE_NEWS_SUCCESS";
export const LANGUAGE_NEWS_ERROR = "LANGUAGE_NEWS_ERROR";
